_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
                - 79
            "2":
                - 1
                - 41
                - 55
                - 79
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
batch_size:
    value: 2
dataset:
    value: normal
distance_threshold:
    value: 5
feature_extractor_lvl_amount:
    value: 8
gaussian_blur:
    value: true
global_image_size:
    value:
        - 600
        - 600
hourglass_stacks:
    value: 4
learning_rate:
    value: 0.00342
model:
    value: UNet
num_channels:
    value: 3
num_epochs:
    value: 15
only_validate:
    value: false
post_processing_threshold:
    value: 0.4
start_from_checkpoint:
    value: false
val_batch_size:
    value: 2
val_model_path:
    value: dynamic_corner_detector.pth
