model {
  file: "model.sdf"
}
name: "Blue_Jasmine_Includes_Digital_Copy_UltraViolet_DVD"
description: "Blue Jasmine [Includes Digital Copy] [UltraViolet] [DVD]"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Sony Pictures"
}
annotations {
  key: "gtin"
  value: "00043396425620"
}
annotations {
  key: "sku"
  value: "00043396425620"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Media Cases"
}
