model {
  file: "model.sdf"
}
name: "adiZero_Slide_2_SC"
description: "adiZero Slide 2 SC\nFW-SLIDES"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "adidas"
}
annotations {
  key: "gtin"
  value: "887383595275"
}
annotations {
  key: "sku"
  value: "M17946"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Shoe"
}
