_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
                - 79
            "2":
                - 1
                - 41
                - 55
                - 79
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
batch_size:
    value: 16
dataset:
    value: cropped_objects
distance_threshold:
    value: 5
feature_extractor_lvl_amount:
    value: 5
gaussian_blur:
    value: true
global_image_size:
    value:
        - 700
        - 700
hourglass_stacks:
    value: 4
learning_rate:
    value: 0.0001
model:
    value: KeyNet
num_channels:
    value: 3
num_epochs:
    value: 20
post_processing_threshold:
    value: 0.4
start_from_checkpoint:
    value: false
val_batch_size:
    value: 16
