model {
  file: "model.sdf"
}
name: "Balderdash_Game"
description: "Balderdash Game"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Mattel Games"
}
annotations {
  key: "gtin"
  value: "00887961060515"
}
annotations {
  key: "sku"
  value: "887961060515"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Board Games"
}
