model {
  file: "model.sdf"
}
name: "Asus_M5A78LMUSB3_Motherboard_Micro_ATX_Socket_AM3"
description: "Asus M5A78L-M/USB3 Motherboard Micro ATX Socket AM3+"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Asus"
}
annotations {
  key: "gtin"
  value: "00610839181117"
}
annotations {
  key: "sku"
  value: "610839181117"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
