model {
  file: "model.sdf"
}
name: "3M_Antislip_Surfacing_Light_Duty_White"
description: "3M Antislip Surfacing; Light Duty; White"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "3M"
}
annotations {
  key: "gtin"
  value: "00051131703315"
}
annotations {
  key: "sku"
  value: "00051131703315"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
