model {
  file: "model.sdf"
}
name: "AMBERLIGHT_UP_W"
description: "AMBERLIGHT UP W"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Adidas"
}
annotations {
  key: "gtin"
  value: "886837773863"
}
annotations {
  key: "mpn"
  value: "g95640"
}
annotations {
  key: "sku"
  value: "G95640"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Shoe"
}
