model {
  file: "model.sdf"
}
name: "45oz_RAMEKIN_ASST_DEEP_COLORS"
description: "4.5oz RAMEKIN ASST DEEP COLORS"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "4.5oz"
}
annotations {
  key: "gtin"
  value: "00033805684090"
}
annotations {
  key: "sku"
  value: "00033805684090"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
