model {
  file: "model.sdf"
}
name: "Big_Dot_Aqua_Pencil_Case"
description: "Big Dot Aqua Pencil Case"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Wildkin"
}
annotations {
  key: "gtin"
  value: "097277391191"
}
annotations {
  key: "mpn"
  value: "39119"
}
annotations {
  key: "sku"
  value: "39119"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Bag"
}
